[tool.poetry]
name = "acacore"
version = "0.1.0"
description = ""
authors = ["Matteo Campinoti <matteo.campinoti94@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.1.1"
sqlalchemy = "~1.3"
databases = {version= "<0.5.0", extras = ["sqlite"]}
sqlalchemy-utils = ">=0.36.8,<0.39.0"
tqdm = "^4.66.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
