name: Linting & Test

on:
    push

env:
  PYTHON_VERSION: 3.10.13
  POETRY_VERSION: 1.6.1

jobs:
    linting:
        uses: aarhusstadsarkiv/acautils/.github/workflows/linting_ruff-mypy.yml@main
    pytest:
        name: pytest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: ${{ env.POETRY_VERSION }}
            - run: |
                  poetry install
            - name: Unit test
              run: |
                poetry run coverage run -m pytest
                poetry run coverage report -m --fail-under=80 --skip-empty --skip-covered
