name: Linting & Test

on:
    push

jobs:
    call-linting-from-utils:
        uses: aarhusstadsarkiv/acautils/.github/workflows/linting_ruff-mypy.yml@main
    pytest:
        name: pytest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - uses: abatilo/actions-poetry@v2.0.0
              with:
                  poetry-version: ${{ env.POETRY_VERSION }}
            - run: |
                  poetry install
            - name: Unit test
              env:
                  TEST_DATA: ${{ secrets.TEST_DATA }}
                  TEST_USER: ${{ secrets.TEST_USER }}
                  TEST_SUBMISSION: ${{ secrets.TEST_SUBMISSION }}
                  TEST_JOURNAL: ${{ secrets.TEST_JOURNAL }}
              run: |
                poetry run coverage run -m pytest
                poetry run coverage report -m --fail-under=80 --skip-empty --skip-covered
