name: Linting & Test

on:
  push

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv sync --all-extras --dev
      - name: ruff check
        run: uv run ruff check src
      - name: ruff format
        run: uv run ruff format --check src

  version:
    name: Test Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          version_project="$(grep --color=never 'version *= *".*"' pyproject.toml)"
          version_project="${version_project%\"}"
          version_project="${version_project#*\"}"
          version_package="$(grep --color=never '__version__ *= *".*"' src/*/__version__.py)"
          version_package="${version_package%\"}"
          version_package="${version_package#*\"}"
          test "$version_project" = "$version_package"

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    needs:
      - linting
      - version
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - uses: actions/setup-go@v5
      - run: uv sync --all-extras --dev
      - run: go install github.com/richardlehane/siegfried/cmd/sf@latest
      - name: pytest
        env:
          GOPATH: /home/runner/go
        run: uv run coverage run -m pytest
      - name: coverage
        run: uv run coverage report -m --fail-under=80 --skip-empty --skip-covered
